from workforce.views.cancel_work_event import cancel_work_event
from workforce.views.welcome_page import WelcomePage
from workforce.views.choose_timeslot import choose_timeslot_page
from workforce.views.user_registration import RegisterUser
from workforce.views.reservation_success import reservation_success
from workforce.views.my_schedule import get_my_schedule, get_my_schedule_hash
