# Generated by Django 3.0.4 on 2020-03-30 22:58

from django.db import migrations, models
import django.db.models.deletion
import workforce.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=200)),
                ('photo', models.ImageField(upload_to=workforce.utils.build_path_for_user_picture)),
            ],
        ),
        migrations.CreateModel(
            name='WorkEvent',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.Calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.User')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=200)),
                ('on_vacations', models.BooleanField(default=False, verbose_name='Disconsider worker when looking for free timeslots')),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.IntegerField(choices=[(0, ''), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.Worker')),
            ],
        ),
    ]
