# Generated by Django 3.0.4 on 2020-03-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
