# Generated by Django 3.0.4 on 2020-06-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workevent',
            name='cancelling_token',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
