# Generated by Django 3.0.4 on 2020-03-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_calendar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='calendar',
        ),
        migrations.AddField(
            model_name='worker',
            name='calendar_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='timezone',
            field=models.CharField(default='America/Sao_Paulo', max_length=200),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
