# Generated by Django 3.0.4 on 2020-03-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_auto_20200322_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='calendar_id',
        ),
        migrations.AddField(
            model_name='worker',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.Calendar'),
        ),
    ]
