# Generated by Django 3.2.7 on 2021-09-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_auto_20210911_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Trabalhadora', 'verbose_name_plural': 'Trabalhadoras'},
        ),
        migrations.AddField(
            model_name='workevent',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='workevent',
            constraint=models.UniqueConstraint(fields=('start', 'calendar_id', 'user_id'), name='idx_event_start_calendar_user'),
        ),
    ]
