# Generated by Django 3.0.4 on 2020-03-31 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_remove_worker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='name',
        ),
    ]
