# Generated by Django 3.2.7 on 2021-09-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_auto_20210911_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='workevent',
            name='canceled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workevent',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(help_text='Nós vamos te enviar um email com um lembrete antes do início da sessão.', max_length=254, unique=True, verbose_name='Endereço de email'),
        ),
        migrations.AlterField(
            model_name='workevent',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='Presencial'),
        ),
    ]
