# Generated by Django 3.0.4 on 2020-03-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='on_vacations',
            field=models.BooleanField(default=False, verbose_name='Desconsider worker when looking for free timeslots'),
        ),
    ]
