# Generated by Django 3.2.7 on 2021-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_auto_20210919_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workevent',
            name='canceled_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
