# Generated by Django 3.0.4 on 2020-03-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_worker_on_vacations'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='on_vacations',
            field=models.BooleanField(default=False, verbose_name='Disconsider worker when looking for free timeslots'),
        ),
        migrations.CreateModel(
            name='WorkEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.Calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.User')),
            ],
        ),
    ]
