# Generated by Django 3.2.7 on 2021-09-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_alter_workevent_canceled_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workevent',
            name='idx_event_start_calendar_user',
        ),
        migrations.AddConstraint(
            model_name='workevent',
            constraint=models.UniqueConstraint(condition=models.Q(('canceled_at', None)), fields=('start', 'calendar_id', 'user_id'), name='idx_active_event_start_calendar_user'),
        ),
    ]
