# Generated by Django 3.0.4 on 2020-03-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_auto_20200331_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workevent',
            name='name',
        ),
        migrations.AddField(
            model_name='workevent',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
