# Generated by Django 3.2.7 on 2021-09-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0008_auto_20210924_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Patient',
        ),
    ]
