# Generated by Django 3.0.4 on 2020-03-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0008_auto_20200323_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_address',
        ),
    ]
