# Generated by Django 3.2.7 on 2021-09-26 18:41

from django.db import migrations


def change_user_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')

    ct = ContentType.objects.filter(
        app_label='auth',
        model='user'
    ).first()

    if ct:
        ct.app_label = 'workforce'
        ct.model = 'my_user'
        ct.save()


def reverse_change(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')

    ct = ContentType.objects.filter(
        app_label='workforce',
        model='my_user'
    ).first()

    if ct:
        ct.app_label = 'auth'
        ct.model = 'user'
        ct.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_rename_user_patient'),
    ]

    operations = [
        migrations.RunPython(change_user_type, reverse_change),
    ]
