# Generated by Django 3.0.4 on 2020-03-27 01:07

from django.db import migrations, models
import workforce.utils


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_auto_20200323_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workevent',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=workforce.utils.build_path_for_user_picture),
        ),
        migrations.AlterField(
            model_name='workevent',
            name='event_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Google agenda event ID'),
        ),
    ]
