# Generated by Django 3.0.4 on 2020-03-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_auto_20200327_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Sao_Paulo', max_length=200),
        ),
    ]
