# Generated by Django 3.2.7 on 2021-09-26 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_users(apps, schema_editor):
    Patient = apps.get_model('workforce', 'Patient')
    MyUser = apps.get_model('workforce', 'MyUser')

    for patient in Patient.objects.all():
        patient.auth_user = MyUser.objects.create_user(
            username=patient.email_address,
            email=patient.email_address,
            first_name=patient.full_name,
            first_login=True,
            password=MyUser.objects.make_random_password(length=30),
        )
        patient.save()


def delete_users(apps, schema_editor):
    Patient = apps.get_model('workforce', 'Patient')
    for patient in Patient.objects.all():
        user = patient.auth_user
        patient.auth_user = None
        patient.save()
        user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0011_alter_myuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_login',
            field=models.BooleanField('Primeiro login?', default=False)
        ),
        migrations.AddField(
            model_name='patient',
            name='auth_user',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_users, delete_users),
        migrations.AlterField(
            model_name='patient',
            name='auth_user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
