# Generated by Django 3.2.7 on 2021-09-27 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_patient_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='auth_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
