# Generated by Django 3.2.7 on 2021-10-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0014_auto_20211009_1137'),
    ]

    operations = [
        migrations.operations.RunSQL(
            'alter table auth_user_groups rename column user_id to myuser_id'
        )
    ]
