# Generated by Django 3.2.7 on 2021-10-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0015_auto_20211009_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
