# Generated by Django 3.2.11 on 2022-04-17 20:01

from django.db import migrations


def create_users(apps, schema_editor):
    Patient = apps.get_model('workforce', 'Patient')
    MyUser = apps.get_model('workforce', 'MyUser')

    for patient in Patient.objects.filter(auth_user__isnull=True).all():
        patient.auth_user = MyUser.objects.create_user(
            username=patient.email_address,
            email=patient.email_address,
            first_name=patient.full_name,
            first_login=True,
            password=MyUser.objects.make_random_password(length=30),
        )
        patient.save()


def delete_users(apps, schema_editor):
    Patient = apps.get_model('workforce', 'Patient')
    for patient in Patient.objects.filter(first_login=True).all():
        user = patient.auth_user
        patient.auth_user = None
        patient.save()
        user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0016_alter_myuser_options'),
    ]

    operations = [
        migrations.RunPython(create_users, delete_users),
    ]
