# Generated by Django 3.2.23 on 2024-02-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0020_auto_20240203_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='validity_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Válido até'),
        ),
    ]
